In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
BASE_DIR = Path.cwd().parent

DATA_DIR = BASE_DIR / "Data"

In [3]:
customers = pd.read_csv(DATA_DIR/"olist_customers_dataset.csv")
orders = pd.read_csv(DATA_DIR/"olist_orders_dataset.csv")
order_items = pd.read_csv(DATA_DIR/"olist_order_items_dataset.csv")
payments = pd.read_csv(DATA_DIR/"olist_order_payments_dataset.csv")
reviews = pd.read_csv(DATA_DIR/"olist_order_reviews_dataset.csv")

In [4]:
datasets = {
    "Customers": customers,
    "Orders": orders,
    "Order Items": order_items,
    "Payments": payments,
    "Reviews": reviews
}

In [5]:
for name, df in datasets.items():
    print(f"{name:<15} {df.shape}")

Customers       (99441, 5)
Orders          (99441, 8)
Order Items     (112650, 7)
Payments        (103886, 5)
Reviews         (99224, 7)

In [6]:
for name, df in datasets.items():

    print("="*60)

    print(name)

    print("="*60)

    print(df.isnull().sum())

    print()

============================================================
Customers
============================================================
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

============================================================
Orders
============================================================
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

============================================================
Order Items
============================================================
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

============================================================
Payments
============================================================
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

============================================================
Reviews
============================================================
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [7]:
for name, df in datasets.items():

    print("="*60)

    print(name)

    print("="*60)

    missing = df.isnull().sum()

    percent = round(missing/len(df)*100,2)

    report = pd.DataFrame({
        "Missing Values":missing,
        "Percentage":percent
    })

    print(report)

    print()

============================================================
Customers
============================================================
                          Missing Values  Percentage
customer_id                            0         0.0
customer_unique_id                     0         0.0
customer_zip_code_prefix               0         0.0
customer_city                          0         0.0
customer_state                         0         0.0

============================================================
Orders
============================================================
                               Missing Values  Percentage
order_id                                    0        0.00
customer_id                                 0        0.00
order_status                                0        0.00
order_purchase_timestamp                    0        0.00
order_approved_at                         160        0.16
order_delivered_carrier_date             1783        1.79
order_delivered_customer_date            2965        2.98
order_estimated_delivery_date               0        0.00

============================================================
Order Items
============================================================
                     Missing Values  Percentage
order_id                          0         0.0
order_item_id                     0         0.0
product_id                        0         0.0
seller_id                         0         0.0
shipping_limit_date               0         0.0
price                             0         0.0
freight_value                     0         0.0

============================================================
Payments
============================================================
                      Missing Values  Percentage
order_id                           0         0.0
payment_sequential                 0         0.0
payment_type                       0         0.0
payment_installments               0         0.0
payment_value                      0         0.0

============================================================
Reviews
============================================================
                         Missing Values  Percentage
review_id                             0        0.00
order_id                              0        0.00
review_score                          0        0.00
review_comment_title              87656       88.34
review_comment_message            58247       58.70
review_creation_date                  0        0.00
review_answer_timestamp               0        0.00

In [8]:
for name, df in datasets.items():

    print(name)

    print(df.duplicated().sum())

Customers
0
Orders
0
Order Items
0
Payments
0
Reviews
0

In [9]:
customers[customers.duplicated()]

Empty DataFrame
Columns: [customer_id, customer_unique_id, customer_zip_code_prefix, customer_city, customer_state]
Index: []

In [10]:
orders.dtypes

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

In [11]:
date_columns = [

    "order_purchase_timestamp",

    "order_approved_at",

    "order_delivered_carrier_date",

    "order_delivered_customer_date",

    "order_estimated_delivery_date"

]

In [12]:
for column in date_columns:

    orders[column] = pd.to_datetime(
        orders[column],
        errors="coerce"
    )

In [13]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[us](5), str(3)
memory usage: 6.1 MB

In [14]:
orders["customer_id"].isin(
    customers["customer_id"]
).all()

np.True_

In [15]:
payments["order_id"].isin(
    orders["order_id"]
).all()

np.True_

In [17]:
summary = []

for name, df in datasets.items():
    summary.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Duplicates": df.duplicated().sum(),
        "Missing Values": df.isnull().sum().sum()
    })

quality_report = pd.DataFrame(summary)
quality_report

       Dataset    Rows  Columns  Duplicates  Missing Values
0    Customers   99441        5           0               0
1       Orders   99441        8           0            4908
2  Order Items  112650        7           0               0
3     Payments  103886        5           0               0
4      Reviews   99224        7           0          145903

In [18]:
CLEAN_DIR = BASE_DIR / "Clean_Data"

CLEAN_DIR.mkdir(exist_ok=True)

In [19]:
customers.to_csv(
    CLEAN_DIR/"customers_clean.csv",
    index=False
)